apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: be-geomaps-php
  name: be-geomaps-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-geomaps-php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: be-geomaps-php
    spec:
      containers:
      - image: razeonex/geomaps-php:v0.1.1
        name: geomaps-php
        resources: {}
status: {}