apiVersion: v1
kind: Service
metadata:
  labels:
    app: be-geomaps-php
  name: geomaps-php-svc
  namespace: geomaps
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: be-geomaps-php
  sessionAffinity: None
  type: ClusterIP
